runMode: local
server:
  HttpPort: 8080
  readTimeOut: 10
  writeTimeOut: 10
database:
  type: mysql
  user: root
  password: 348521409
  host: 127.0.0.1
  dbname: qiniu
  network: tcp
  port: 3307
logPath: logfile/